### PR TITLE
Merge tv branch

### PR DESCRIPTION
**Pull request by rhenwinch**
this should be ready for pre-releases.

### CODE REVIEW

**Comment by oathzed** [comment]
;O can we please get an apk built for this one for testing? :D

**Comment by rhenwinch** [comment]
> ;O can we please get an apk built for this one for testing? :D

A debug or a 'prerelease' build type? I can update the workflow to have a custom release type so it wont bother your current release data

**Comment by rhenwinch** [comment]
Oh. I just realized the CI failed lol

**Comment by oathzed** [comment]
> Oh. I just realized the CI failed lol

Haha I saw that in the actions tab, but I tried building the source code in android studio with no luck 😂

**Comment by oathzed** [comment]
> > ;O can we please get an apk built for this one for testing? :D
> 
> A debug or a 'prerelease' build type? I can update the workflow to have a custom release type so it wont bother your current release data

That might be good, but it's ok if it's too much work

**Comment by oathzed** [comment]
> > I tried building the source code in android studio with no luck
> 
> If u could open an issue, will appreciate it! so I know why devs cant contribute.
> 
> also, a github feature issue would be appreciated as well if ever the repo is still not _open-source friendly._ :')

Hey man, sorry for the late reply, I've been busy with work.
I've just submitted an issue, it seems when I  go to the build menu, it doesn't give me the option to build the apk for debugging testing. but in android studio it says build successful when I imported the source code.

Forgive me but I'm not an app dev, I just like to tinker with this kind of stuff :P.

https://github.com/rhenwinch/Flixclusive/issues/49

**Pull request merged**
